### ISSUE TITLE
Cannot build out of the box latest 0.3.6.

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#392] opened 2022-06-11 13:34 UTC
## Description
I like to test an "out of the box" build before adding any changes to my projects. This one does not work, and I could not find the reasons why. Things done in the past when it would not build OOB did not work this time. I spent several hours trying to work out the issues with the build.

Trying to build out of the box following the instructions. There is a problem with the OpenXR version 1.0.22. The first error is a pathspec xxxxxxxx is not a known path in git.
It also complains that the CMakelists.txt file is missing from the tools folder. (copying the file there does not fix the issue)
After that error I get a collection of errors.
Interestingly I had several problems with the shaderxxxxxx.h files having syntax errors. I tried downloading new clones and starting over from the beginning and the syntax errors seemed to move around, like the decompression was corrupt. There would be sequences like this in the files:
...
11,
116,
,
23,
...
and 
...
11,
116,
};
,
45,
123,
...

In any case I was not able to build successfully. 

## Platform / Environment
Windows 11 with Visual Studio 2022 both latest version. I am currently using SK 0.3.5 with no issues.

## Logs or exception details
```
Attached the error log and the build raw output.

_If you have an exception, details about that would also be essential._
[SK0-3-6_build errors list.zip](https://github.com/StereoKit/StereoKit/files/8883970/SK0-3-6_build.errors.list.zip)

**Comment by maluoi** [comment] 2022-06-13 00:12
This looks a lot like what I mentioned over in the comments [on this PR](https://github.com/StereoKit/StereoKit/pull/379#issuecomment-1153317669)! I'll be looking into this issue soon, but you may also want to try deleting `/Tools/oxr_current.txt`

**Comment by paulmelis** [comment] 2022-06-13 06:56
Removing `Tools/oxr_current.txt` indeed seems to force a correct build of reactphysics3d. However, I'm also seeing the git error related to OpenXR mentioned by OP (`pathspec 'release-1.0.22' did not match any file(s) know to git`). Plus a slew of `The source directory ".../Tools/OpenXR-SDK" does not appear to contain CMakeLists.txt"`, but maybe those are fallout of the git error.

**Comment by paulmelis** [comment] 2022-06-13 13:23
One issue I think is that 

https://github.com/StereoKit/StereoKit/blob/f5e16a18c0c35aa18055cc6ba9ccec75802492f8/Tools/Update-OpenXR.ps1#L211-L219

try to copy libraries to an `ARM` directory, but that is never created?

**Comment by maluoi** [comment] 2022-06-14 04:44
Okaaay! Took me all day, but I reworked the powershell stuff completely in `/develop` :) It's a much nicer system! This no longer builds _all_ architectures and flavors at once, just the ones you need, when you need them. Should also be a lot better at detecting when it needs a rebuild, and will build much faster in most cases.

I didn't touch anything with the shaders here, so any issues related to that will probably not be fixed from this. I'll be looking at those next. But in the meantime, I'd definitely appreciate any feedback as to whether this improved the situation for you!

**Comment by paulmelis** [comment] 2022-06-14 07:23
Could you describe which build recipe you would expect to work? I just checked out a clean `develop` repo and then did these steps:

1. Start VS (community 2022, 17.1.2), load StereoKit.sln
2. Click OK for the unsupported `StereoKitTest_Android.csproj`, and close migration report in the browser
3. Set build mode to `Release` and CPU to `x64`
4. Verify that `StereoKitTest` is the startup project
5. Ignore the "Current solution contains incorrect configurations mappings" (I guess these are the UWP projects)?
6. Choose `Build > Build StereoKitTest`

The build finishes without errors, yet when I run it on the XR-3 I get `[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]` errors. I don't know if this is due to the build system changes or something else. See below for full output. My usual SK-based viewer still works, btw, so it's not the Varjo setup.

```
[SK diagnostic] Initializing StereoKit v0.3.6 Win32 x64...
[SK diagnostic] Initializing Assets
[SK diagnostic] Initializing Platform
20220614 9:19:56.415 --- [Varjo::RuntimeInterface::load] Trying to load VarjoRuntime from "C:\Users\VR-1\Desktop\Projects\StereoKit-develop\bin\x64_Release\StereoKitTest\VarjoRuntime.dll"...
20220614 9:19:56.415 --- [Varjo::RuntimeInterface::load] Trying to load VarjoRuntime from "\VarjoRuntime.dll"...
20220614 9:19:56.415 --- [Varjo::RuntimeInterface::load] Trying to load VarjoRuntime from "C:\Program Files\Varjo\varjo-compositor\\VarjoRuntime.dll"...
20220614 9:19:56.417 --- [Varjo::RuntimeInterface::load] VarjoRuntime.dll loaded from C:\Program Files\Varjo\varjo-compositor\\VarjoRuntime.dll successfully.
20220614 9:19:56.417 --- [PipeSession::Run] Pipe1: Open
20220614 9:19:56.417 --- [PipeClient::OnSessionStart] Connected.
20220614 9:19:56.418 --- [PipeSession::Run] Pipe1: Disconnected
20220614 9:19:56.418 --- [Varjo::CreateAndInitSession] clientSessionId: sdk#openxr#1000001849193660700, version: 3.5.1.720220614 9:19:56.418 --- [PipeSession::Run] Pipe2: Open
20220614 9:19:56.418 --- [PipeClient::OnSessionStart] Connected.
20220614 9:19:56.419 --- [PipeSession::Run] Pipe2: Disconnected
20220614 9:19:56.419 --- [Varjo::LayerClient::LayerClient] New LayerClient, unique client session id: 'sdk#openxr#1000001849193660700', sdk version='3.5.1.7'
20220614 9:19:56.423 --- [Varjo::HighPrecisionSleep::initialize::<lambda_5b1c913cccf0cf71e84d2cc3abb4d395>::operator ()] HPSleep resolution: 499900 ns
20220614 9:19:56.423 --- [PipeSession::Run] Pipe3: Open
20220614 9:19:56.424 --- [PipeClient::OnSessionStart] Connected.
20220614 9:19:56.425 --- [Varjo::LayerClient::waitHandshake] Wait for handshake
20220614 9:19:56.426 --- [Varjo::LayerClient::waitHandshake] HANDSHAKE OK
20220614 9:19:56.426 *** [Varjo::LayerClient::waitHandshake] result OK
20220614 9:19:56.428 --- [Varjo::Session::createCompositorLink] Create compositor link for sdk#openxr#1000001849193660700
20220614 9:19:56.428 --- [Varjo::LayerClient::createIPCAndWait] createIPCAndWait...
20220614 9:19:56.430 --- [Varjo::LayerClient::createIPCAndWait] createIPCAndWait... OK.
20220614 9:19:56.434 --- [Varjo::GazeClient::connectionThread] GazeClient 'VarjoSystem.FoveatedViewManager' with output frequency DeviceHz and smoothing ON successfully connected to suitable gaze IPC stream
20220614 9:19:56.434 --- [Varjo::GazeClient::connectionThread] GazeClient 'VarjoSystem.FoveatedViewManager.Latency' with output frequency DeviceHz and smoothing ON successfully connected to suitable gaze IPC stream
20220614 9:20:01.472 --- [Varjo::GazeClient::connectionThread] GazeClient 'sdk#openxr#1000001849193660700' with output frequency 100Hz and smoothing ON successfully connected to suitable gaze IPC stream
20220614 9:20:01.473 --- [Varjo::GazeClient::waitConnectionThreadWakeup] GazeClient 'VarjoSystem.FoveatedViewManager.Latency' connection thread woke up
20220614 9:20:01.474 --- [Varjo::GazeClient::waitConnectionThreadWakeup] GazeClient 'VarjoSystem.FoveatedViewManager' connection thread woke up
20220614 9:20:01.474 --- [Varjo::GazeClient::waitConnectionThreadWakeup] GazeClient 'sdk#openxr#1000001849193660700' connection thread woke up
20220614 9:20:01.475 --- [PipeSession::Run] Pipe3: Disconnected
20220614 9:20:01.476 --- [Varjo::RuntimeInterface::unload] No more active sessions, VarjoRuntime unloaded.
[SK diagnostic] sk_gpu: Using Direct3D 11: NVIDIA GeForce RTX 3090
[SK diagnostic] Starting mixed reality mode
[SK diagnostic] available: XR_KHR_opengl_enable
[SK diagnostic] available: XR_VARJO_composition_layer_depth_test
[SK diagnostic] available: XR_VARJO_environment_depth_estimation
[SK diagnostic] available: XR_EXT_debug_utils
[SK diagnostic] available: XR_EXT_win32_appcontainer_compatible
[SK diagnostic] available: XR_VARJO_quad_views
[SK diagnostic] available: XR_VARJO_foveated_rendering
[SK diagnostic] available: XR_KHR_visibility_mask
[SK diagnostic] available: XR_VARJO_marker_tracking
[SK diagnostic] available: XR_HTCX_vive_tracker_interaction
[SK diagnostic] REQUESTED: XR_KHR_D3D11_enable
[SK diagnostic] REQUESTED: XR_KHR_win32_convert_performance_counter_time
[SK diagnostic] REQUESTED: XR_KHR_composition_layer_depth
[SK diagnostic] REQUESTED: XR_EXT_eye_gaze_interaction
[SK diagnostic] REQUESTED: XR_EXT_hand_tracking
20220614 9:20:01.533 --- [Varjo::RuntimeInterface::load] Trying to load VarjoRuntime from "C:\Users\VR-1\Desktop\Projects\StereoKit-develop\bin\x64_Release\StereoKitTest\VarjoRuntime.dll"...
20220614 9:20:01.533 --- [Varjo::RuntimeInterface::load] Trying to load VarjoRuntime from "\VarjoRuntime.dll"...
20220614 9:20:01.533 --- [Varjo::RuntimeInterface::load] Trying to load VarjoRuntime from "C:\Program Files\Varjo\varjo-compositor\\VarjoRuntime.dll"...
20220614 9:20:01.535 --- [Varjo::RuntimeInterface::load] VarjoRuntime.dll loaded from C:\Program Files\Varjo\varjo-compositor\\VarjoRuntime.dll successfully.
20220614 9:20:01.535 --- [PipeSession::Run] Pipe1: Open
20220614 9:20:01.535 --- [PipeClient::OnSessionStart] Connected.
20220614 9:20:01.536 --- [PipeSession::Run] Pipe1: Disconnected
20220614 9:20:01.537 --- [Varjo::CreateAndInitSession] clientSessionId: sdk#openxr#1000001854311976100, version: 3.5.1.720220614 9:20:01.537 --- [PipeSession::Run] Pipe2: Open
20220614 9:20:01.537 --- [PipeClient::OnSessionStart] Connected.
20220614 9:20:01.538 --- [PipeSession::Run] Pipe2: Disconnected
20220614 9:20:01.538 --- [Varjo::LayerClient::LayerClient] New LayerClient, unique client session id: 'sdk#openxr#1000001854311976100', sdk version='3.5.1.7'
20220614 9:20:01.538 --- [Varjo::HighPrecisionSleep::initialize::<lambda_5b1c913cccf0cf71e84d2cc3abb4d395>::operator ()] HPSleep resolution: 499900 ns
20220614 9:20:01.539 --- [PipeSession::Run] Pipe3: Open
20220614 9:20:01.539 --- [PipeClient::OnSessionStart] Connected.
20220614 9:20:01.541 --- [Varjo::LayerClient::waitHandshake] Wait for handshake
20220614 9:20:01.543 --- [Varjo::LayerClient::waitHandshake] HANDSHAKE OK
20220614 9:20:01.543 *** [Varjo::LayerClient::waitHandshake] result OK
20220614 9:20:01.546 --- [Varjo::Session::createCompositorLink] Create compositor link for sdk#openxr#1000001854311976100
20220614 9:20:01.546 --- [Varjo::LayerClient::createIPCAndWait] createIPCAndWait...
20220614 9:20:01.548 --- [Varjo::LayerClient::createIPCAndWait] createIPCAndWait... OK.
20220614 9:20:01.550 --- [Varjo::GazeClient::connectionThread] GazeClient 'VarjoSystem.FoveatedViewManager' with output frequency DeviceHz and smoothing ON successfully connected to suitable gaze IPC stream
20220614 9:20:01.550 --- [Varjo::GazeClient::connectionThread] GazeClient 'VarjoSystem.FoveatedViewManager.Latency' with output frequency DeviceHz and smoothing ON successfully connected to suitable gaze IPC stream
[SK diagnostic] Using system: XR-3
[SK diagnostic] Platform supports single-pass rendering
[SK diagnostic] OpenXR articulated hands ext enabled!
[SK diagnostic] OpenXR depth LSR ext enabled!
20220614 9:20:01.551 --- [Varjo::GazeClient::connectionThread] GazeClient 'sdk#openxr#1000001854311976100' with output frequency 100Hz and smoothing ON successfully connected to suitable gaze IPC stream
[SK diagnostic] OpenXR gaze ext enabled!
20220614 9:20:01.552 --- [Varjo::HandTrackingClient::start] Start HandTrackingClient
20220614 9:20:01.552 --- [Varjo::HandTrackingClient::process] HandTrackingSource thread started
[SK diagnostic] Creating view: PrimaryStereo color:rgba32_linear depth:depth32 blend:Alpha Blend
20220614 9:20:01.552 --- [Varjo::HandTrackingClient::process] (skipped 0) Waiting for IPC input Varjo.HandTracking.TrackedHands connection...
20220614 9:20:01.552 --- [Varjo::CreateAndInitSession] clientSessionId: sdk#openxr#1000001854327564100, version: 3.5.1.720220614 9:20:01.553 --- [PipeSession::Run] Pipe4: Open
20220614 9:20:01.553 --- [PipeClient::OnSessionStart] Connected.
20220614 9:20:01.553 --- [PipeSession::Run] Pipe4: Disconnected
20220614 9:20:01.554 --- [Varjo::LayerClient::LayerClient] New LayerClient, unique client session id: 'sdk#openxr#1000001854327564100', sdk version='3.5.1.7'
20220614 9:20:01.554 --- [PipeSession::Run] Pipe5: Open
20220614 9:20:01.554 --- [PipeClient::OnSessionStart] Connected.
20220614 9:20:01.556 --- [Varjo::LayerClient::waitHandshake] Wait for handshake
20220614 9:20:01.559 --- [Varjo::LayerClient::waitHandshake] HANDSHAKE OK
20220614 9:20:01.559 *** [Varjo::LayerClient::waitHandshake] result OK
20220614 9:20:01.561 --- [Varjo::Session::createCompositorLink] Create compositor link for sdk#openxr#1000001854327564100
20220614 9:20:01.561 --- [Varjo::LayerClient::createIPCAndWait] createIPCAndWait...
20220614 9:20:01.563 --- [Varjo::LayerClient::createIPCAndWait] createIPCAndWait... OK.
20220614 9:20:01.566 --- [Varjo::GazeClient::connectionThread] GazeClient 'VarjoSystem.FoveatedViewManager' with output frequency DeviceHz and smoothing ON successfully connected to suitable gaze IPC stream
20220614 9:20:01.566 --- [Varjo::GazeClient::connectionThread] GazeClient 'VarjoSystem.FoveatedViewManager.Latency' with output frequency DeviceHz and smoothing ON successfully connected to suitable gaze IPC stream
[SK diagnostic] Setting view: PrimaryStereo to 4148x3556
20220614 9:20:01.572 --- [Varjo::Session::createSwapChain] Varjo::Session::createSwapChain, client: sdk#openxr#1000001854311976100
20220614 9:20:01.575 --- [Varjo::LayerClient::createSwapChain] createSwapchain... OK.
20220614 9:20:01.575 --- [Varjo::Session::createSwapChain] Varjo::Session::createSwapChain, client: sdk#openxr#1000001854311976100
20220614 9:20:01.577 --- [Varjo::LayerClient::createSwapChain] createSwapchain... OK.
[SK diagnostic] Bounds updated: 0.00x0.00 at (0.0,0.0,0.0) (0.00,0.00,0.00,1.00)
[SK diagnostic] Initializing Audio
[SK diagnostic] ISAC audio backend not available, falling back to miniaudio! It's likely the device doesn't have Windows Sonic enabled, which can be found under Settings->Sound->Device Properties->Spatial Sound.
[SK info] Using audio backend: WASAPI
[SK diagnostic] Initializing Defaults
[SK diagnostic] Initializing World
[SK diagnostic] Initializing Sprites
[SK diagnostic] Initializing Lines
[SK diagnostic] Initializing UI
[SK diagnostic] Initializing Renderer
[SK diagnostic] Initializing Physics
[SK diagnostic] Initializing Input
[SK info] Initialization successful
[SK info] XrTime: 18543561344
[SK diagnostic] sprite_create: Atlased sprites not implemented yet! Switching to single.
[SK info] Starting Scene: DemoWelcome
[SK diagnostic] OpenXR session begin.
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] App focus changed to: Background
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] App focus changed to: Active
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
[SK info] xrEndFrame [XR_ERROR_LAYER_INVALID]
```

**Comment by jefmes** [comment] 2022-06-14 08:30
I don't know if it's helpful here at all, but I tried to do the same process Paul is trying here and ran into a different problem around the PS scripts checking that I have cmake installed. I noticed that opening the standard OS PowerShell (7.2.4) and trying "get-command cmake" it's not recognized. If I open the Developer PowerShell for VS 2022 though it works fine. So for some reason at least in my config the Build process for StereoKitTest is looking at the wrong paths or the "Update-Dependencies.ps1" process isn't aware of the VS 2022 install process putting cmake into a seperate, dedicated path? I'm not too familiar with cmake overall so this is my first time looking at errors with it. My path looks correct so I'm not quite sure what's going on here just yet.

**Comment by jefmes** [comment] 2022-06-14 08:40
> @jefmes I simply downloaded CMake from [www.cmake.org](http://www.cmake.org) and used the Windows installer (and let CMake get added to PATH during install)

Interesting, I was going to go that route but when I noticed the VS role for cmake was available in the "Desktop development with C++" Workload option in Visual Studio, I assumed it would add those relationships and make cmake and msbuild available in the PATH directly. That might be something worth considering either way from an ease of use point perspective for other users coming to StereoKit in Visual Studio. That said - I'd bet the majority of users won't be trying to build SK themselves, and if they are they'd likely do the same and just install cmake themselves and be done with it. :)

**Comment by maluoi** [comment] 2022-06-14 17:40
> I noticed that opening the standard OS PowerShell (7.2.4) and trying "get-command cmake" it's not recognized. If I open the Developer PowerShell for VS 2022 though it works fine.

This is a really great point! I've got cmake in my path regardless, since I kinda need it for a whole pile of things, and I do call out needing cmake in the [building guide](https://github.com/StereoKit/StereoKit/blob/master/BUILDING.md) because of this. But it should be possible to snag a cmake from Visual Studio's install in some cases! That might smooth the path out a bit more for people :)

I'll look into that. If it's not too hard to add, that seems like a nice win!

> The build finishes without errors, yet when I run it on the XR-3 I get [SK info] xrEndFrame [XR_ERROR_LAYER_INVALID] errors. I don't know if this is due to the build system changes or something else. See below for full output. My usual SK-based viewer still works, btw, so it's not the Varjo setup that's at fault.
>
> Edit: does the develop branch use a newer version of the OpenXR SDK? If so, I guess that could explain this?

I didn't see anything that jumps out in the commit log between here and there! But I'll definitely investigate this with the Varjo simulator, see if I can repro it there :) Does this happen with the v0.3.6 build on NuGet, or is it just custom builds on `/develop`?

**Comment by maluoi** [comment] 2022-06-15 00:31
Okay, good news is I _can_ reproduce the Varjo issue in the simulator, and it does seem to be specific to the `/develop` branch! The main NuGet package works still, so this could indeed be related to the recent build changes. Odd!

Anyhow, if I can repro it, I can fix it :) Will probably dig into the meat of that problem tomorrow.

**Comment by maluoi** [comment] 2022-06-15 18:52
@paulmelis, looks like that was actually a bug with the FB Passthrough extension tool in the StereoKitTest project! It was enabling and submitting composition layers even though the extension wasn't available, and that was tripping up Varjo. So, `/develop` should be good with respect to that now.

**Comment by maluoi** [comment] 2022-06-16 01:51
Alright, I've also fixed the issue in the shader compiler as well, so problems there _should_ be fixed now!

I'll try spinning up a VM or something tomorrow to try out building from scratch on a new machine, see if I can catch anything else :) But I think things may be in pretty decent shape right now!

**Comment by laultman** [comment] 2022-06-16 09:43
I've been tracking the progress every day, awesome. I am learning a lot about the StereoKit build process in the interim. I had never looked at the shader compiler process or much of the cmake at all before this update. I have focused my efforts on extending and building a platform on the StereoKit for HoloLens 2. Some of my extensions require tedious surgery on the StereoKit C++. With this new knowledge I hope to be able to avoid some of those surgical procedures by manipulating the build process. I confess that I have avoided this until now. @maluoi I am looking at PSI to help me with the recognition of containers that look identical to human eyes.

**Comment by maluoi** [comment] 2022-06-17 00:31
> I am looking at PSI to help me with the recognition of containers that look identical to human eyes.

This sounds amazing! :O

---

I added a few new messages and explicit errors into the build pipeline, so it should be easier to navigate any pitfalls! Building on a VM, it looked like cmake is probably the biggest thing people are likely to run into, but messaging there should be much better :)

@jefmes, I did also get the Visual Studio cmake thing working! Ended being not too tough to implement :) Pretty cool, thanks for the idea!

Barring any tripwires you all run into, I think this will probably wrap up my work on build improvements for now! Android may still be a bit of a task, but I've been salivating quite a bit over some new OpenXR extensions, so I'll come back and revisit that later!

I'll leave this task open for a bit, and will close it later on if nothing else crops up :) I hope this work has helped!

**Comment by laultman** [comment] 2022-06-17 08:34
Not yet pushed out to github is it? Got a fresh copy and it hasn't changed. Only later did I look and see that the last update was 11 days ago.

**Comment by paulmelis** [comment] 2022-06-17 08:35
Did you use the `develop` branch?

**Comment by laultman** [comment] 2022-06-18 11:04
No. I didn't, thanks.

**Closed** 2022-06-30 17:22 UTC
