### ISSUE TITLE
Why does  Stereokit  not have a gesture model on Snapdragon Spaces  

### ISSUE THREAD

**Issue by jike2018** [StereoKit/StereoKit#885] opened 2024-03-01 10:08 UTC
hello, I used VS2022 to create a template project for the Stereokit Android platform, and correctly added the libopenxR_loader.so file. After packaging the APK, it cannot run on Snapdragon Spaces devices. Flashback occurs. How to run correctly？
   
Here are some logs：
--------- beginning of crash
02-01 21:33:44.139  6283  6283 F linker  : CANNOT LINK EXECUTABLE "/system/vendor/bin/qcc-trd": library "vendor.qti.hardware.qccsyshal@1.2.so" not found: needed by main executable
02-01 21:33:44.140     0     0 I init    : Service 'vendor.qcc-trd' (pid 6283) exited with status 1
02-01 21:33:44.140     0     0 I init    : Sending signal 9 to service 'vendor.qcc-trd' (pid 6283) process group...
02-01 21:33:44.140     0     0 I libprocessgroup: Successfully killed process cgroup uid 1000 pid 6283 in 0ms
02-01 21:33:44.152  2890  3036 I OpenXR overlay: AppCommon

02-01 21:33:45.409  2890  3036 I OpenXR overlay: AppCommon
02-01 21:33:45.414  1094  1094 W HwcComposer: command 0x4050000 generated error 4
02-01 21:33:45.421  6291  6321 W monodroid-assembly: Shared library 'StereoKitC' not loaded, p/invoke 'quat_lookat' may fail
02-01 21:33:45.425  1094  1094 W HwcComposer: command 0x4050000 generated error 4
02-01 21:33:45.426  6291  6321 W monodroid-assembly: Shared library 'StereoKitC' not loaded, p/invoke 'quat_lookat' may fail
02-01 21:33:45.429  6291  6321 W monodroid-assembly: Shared library 'StereoKitC' not loaded, p/invoke 'quat_lookat' may fail
02-01 21:33:45.433  1094  1182 W ServiceManager: Permission failure: android.permission.ACCESS_SURFACE_FLINGER from uid=10116 pid=6291
02-01 21:33:45.433  1094  1182 D PermissionCache: checking android.permission.ACCESS_SURFACE_FLINGER for uid=10116 => denied (141 us)
02-01 21:33:45.433  1094  1182 W ServiceManager: Permission failure: android.permission.ROTATE_SURFACE_FLINGER from uid=10116 pid=6291
02-01 21:33:45.433  1094  1182 D PermissionCache: checking android.permission.ROTATE_SURFACE_FLINGER for uid=10116 => denied (91 us)
02-01 21:33:45.434  2097  2097 E OverviewProxyService: Failed to get overview proxy for system bar attr change.
02-01 21:33:45.436  1094  1094 W HwcComposer: command 0x4050000 generated error 4
02-01 21:33:45.437  6291  6291 W monodroid-assembly: Shared library 'StereoKitC' not loaded, p/invoke 'sk_set_window_xam' may fail
02-01 21:33:45.439  6291  6291 W monodroid-assembly: Shared library 'StereoKitC' not loaded, p/invoke 'sk_set_window_xam' may fail
02-01 21:33:45.443  6291  6291 W monodroid-assembly: Shared library 'StereoKitC' not loaded, p/invoke 'sk_set_window_xam' may fail
02-01 21:33:45.445  6291  6321 F mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: TypeInitialization_Type, StereoKit_Test.Program
02-01 21:33:45.445  6291  6321 F mono-rt :  ---> System.DllNotFoundException: StereoKitC
02-01 21:33:45.445  6291  6321 F mono-rt :    at StereoKit_Test.Program..cctor()
02-01 21:33:45.445  6291  6321 F mono-rt :    Exception_EndOfInnerExceptionStack
02-01 21:33:45.445  6291  6321 F mono-rt :    at StereoKit_Test.MainActivity.InvokeStereoKit()
02-01 21:33:45.445  6291  6321 F mono-rt :    at System.Threading.Thread.StartCallback()
02-01 21:33:45.448  1094  1094 W HwcComposer: command 0x4050000 generated error 4
02-01 21:33:45.449  2890  3036 I OpenXR overlay: AppCommon
02-01 21:33:45.459  1094  1094 W HwcComposer: command 0x4050000 generated error 4
02-01 21:33:45.467  1257  4768 I WindowManager: WIN DEATH: Window{fb1f6ca u0 com.companyname.StereoKit_Test/crc64b8ff3140029f9156.MainActivity}
02-01 21:33:45.467  1257  6163 I ActivityManager: Process com.companyname.StereoKit_Test (pid 6291) has died: fg  TOP 
02-01 21:33:45.467  1257  4768 W InputManager-JNI: Input channel object 'fb1f6ca com.companyname.StereoKit_Test/crc64b8ff3140029f9156.MainActivity (client)' was disposed without first being removed with the input manager!
02-01 21:33:45.467   769   769 I Zygote  : Process 6291 exited cleanly (1)
02-01 21:33:45.468  1257  1611 I libprocessgroup: Successfully killed process cgroup uid 10116 pid 6291 in 0ms
02-01 21:33:45.469  1257  6163 W ActivityTaskManager: Force removing ActivityRecord{f501f9d u0 com.companyname.StereoKit_Test/crc64b8ff3140029f9156.MainActivity t137}: app died, no saved state

**Comment by maluoi** [comment] 2024-03-01 16:26
It looks like one or more .so libraries aren't loading! While this states that `libStereoKitC.so` wasn't found, this can often mean a library in StereoKitC's dependency chain wasn't found.

First thing to check is to make sure that `libStereoKitC.so` and `libopenxr_loader.so` are both in the APK. These will be in the `lib/arm64-v8a/` folder when you unzip the APK.

![image](https://github.com/StereoKit/StereoKit/assets/8484884/1b95c214-fdaf-46a7-9e14-41466a546185)

Make sure the `libopenxr_loader.so` file size matches the custom Snapdragon one you provided.

If either of those are missing, make sure you've correctly set up the openxr loader hooks, and make sure Visual Studio isn't caching anything. (uninstall APK, delete bin/obj folders, rebuild project, etc.)

I have heard of some headsets that are either missing `liblog.so`, or something prevents the app from finding `liblog.so`. If you see any mention of this in `adb logcat`, a hack-ey workaround would be to include your own copy of liblog.so with the APK. I don't know what the root cause of this one could be, so I don't have a better solution for this issue yet.

**Comment by jike2018** [comment] 2024-03-05 02:23
I used the following method to add libopenxloader.so
![20240305-101729](https://github.com/StereoKit/StereoKit/assets/48623339/6baddd3a-5e2a-4b6b-aa7e-85da6fc07863)
![20240305-101525](https://github.com/StereoKit/StereoKit/assets/48623339/e63c3559-d10d-4c79-8ddd-59220c04f861)
This is the lib folder in the apk package produced by the VS2022 template project
![3654bc68-e1eb-4ee3-ae91-ea57b9a45570](https://github.com/StereoKit/StereoKit/assets/48623339/5b83f995-b023-493f-a6aa-27141adea593)
Why is there no libopenxloader.so in the lib folder？

**Comment by maluoi** [comment] 2024-03-05 19:19
Check your build logs carefully, and see if anything gets pointed out there! You can also use `<SKShowDebugVars>true</SKShowDebugVars>` to get SK's final build variables logged.

Two other things you could try:
- Use Windows style path separators, `D:\XRSpace\openxr_loaders\`.
- Make sure there's a trailing slash on your folder.

**Comment by jike2018** [comment] 2024-03-08 03:23
Now I can run Stereokit APK normally on Snapdragon devices, but why can't I see the hand model? There is hand output in the log.

This is a Stereokit APK that runs normally on Snapdragon devices without any hand 
![Snipaste_2024-03-08_11-16-11](https://github.com/StereoKit/StereoKit/assets/48623339/2b8a0054-bec3-448b-9c48-01c9fb5106ec)

This is the log output of gestures
![Snipaste_2024-03-08_11-20-06](https://github.com/StereoKit/StereoKit/assets/48623339/74c35479-5f05-4ac7-be1b-273653ab56d2)

This is the code
![Snipaste_2024-03-08_11-22-57](https://github.com/StereoKit/StereoKit/assets/48623339/81ec4de4-b30e-4d4e-bc14-efe6ba207bd5)

Why can't I see the gesture model？

**Closed** 2024-03-12 02:09 UTC
